services:
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./mongodb/data:/data/SBMDB
  data-miner:
    image: sbm-miner
    build:
      context: ./data-miner
    restart: always
    container_name: data-miner
    depends_on:
      - mongodb
    links:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/SBMDB
  data-publisher:
    image: sbm-publisher
    build:
      context: ./data-publisher
    restart: always
    container_name: data-publisher
    depends_on:
      - mongodb
      - data-miner
    links:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/SBMDB